apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
- ingressgateway.yaml
- store-admin-virtualservice.yaml
- store-admin-scaledobject.yaml
- store-front-virtualservice.yaml
- store-front-scaledobject.yaml
namespace: dev
images:
- name: ghcr.io/pauldotyu/aks-store-demo/store-front
  newName: ghcr.io/pauldotyu/aks-store-demo/store-front # {"$imagepolicy": "flux-system:store-front:name"}
  newTag: 1.0.0 # {"$imagepolicy": "flux-system:store-front:tag"}
- name: ghcr.io/pauldotyu/aks-store-demo/store-admin
  newName: ghcr.io/pauldotyu/aks-store-demo/store-admin # {"$imagepolicy": "flux-system:store-admin:name"}
  newTag: 1.0.0 # {"$imagepolicy": "flux-system:store-admin:tag"}