apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: store-admin
spec:
  scaleTargetRef:
    name: store-admin
  minReplicaCount: 1
  maxReplicaCount: 100
  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      value: "90"