apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: ai-service-account
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: order-service
        image: ghcr.io/pauldotyu/aks-store-demo/ai-service:1.2.1
        ports:
        - containerPort: 5001
        envFrom:
        - configMapRef:
            name: ai-service-configs
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 128Mi
        startupProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 40
          failureThreshold: 3
          timeoutSeconds: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 3
          failureThreshold: 10
          timeoutSeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          failureThreshold: 10
          initialDelaySeconds: 3
          timeoutSeconds: 3
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
spec:
  ports:
  - name: http
    port: 5001
    targetPort: 5001
  selector:
    app: ai-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ai-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ai-service
  unhealthyPodEvictionPolicy: AlwaysAllow